### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gaearon** [gaearon/dnd-core#1]
- [x] Implement/test dropping on target (`drop` on drop target, `endDrag(true)` on drag source)
- [x] Implement/test dropping somewhere else (`endDrag(false)` on drag source)
- [x] *Think: should we let `drop` return a value and pass it to `endDrag` instead of a boolean?* **SOLVED:** yep we do that now.

- [x] Implement/test subscription to state (let `DragDropContext` expose `addChangeListener`/`removeChangeListener` that proxies to `DragOperationStore`?), we'll use that in React for [letting components update their state](https://github.com/gaearon/react-dnd/issues/103)

- [x] *Think: consumer may want to “recalculate” drag state at some point. Imagine `canDrop` (we haven't talked about it yet, but it should be implemented at some point) that depends on `props`, and `props` changed. Can React part tell dnd-core that it needs to “reconsider” some stuff it may have calculated concerning a drop zone or drag source?* — **SOLVED:** it is up to consumer to test `canDrop` via `this.context.canDrop(targetHandle)` at any time they find it convenient. dnd-core will throw if the condition is not met when calling `drop`.

- [x] *MY FAVORITE PART (closely related to previous point). You have a list of React components in an array *but without keys*. The items reorder. How to make sure their drag states still match? This might be `canJoinDrag` or some other API that makes more sense. TEST IT.* SOLVED: added `isDragging(context)` to drag source API.

- [x] *Think: how do we go about event bubbling?*

- [x] Figure out how we represent “entered” drop targets (gotta store a list in manager to support nesting, `DragDropContext` will ask the manager to implement `isOver(descriptor)`, `isInside(descriptor)`). Implement and test.

- [ ] Finally, the boring part: tracking drag coordinates.

**Comment by nelix** [comment]
Just thinking about event bubbling, and how to emulate/simulate/facilitate that

**Comment by gaearon** [comment]
Only drag event left!

**Comment by gaearon** [comment]
Closing, we'll track `dragOver` implementation in #6.
We don't know enough to implement it yet.
